services:
    db:
        container_name: db
        image: ghcr.io/identicum/postgres:15
        pull_policy: always
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: identicum
        volumes:
            - ./db/:/docker-entrypoint-initdb.d/:ro
    hr:
        container_name: hr
        image: ghcr.io/identicum/sherpa-hr:latest
        # pull_policy: always
        restart: always
        ports:
            - 80:5000
        environment:
            POSTGRES_DB: hrdb
            POSTGRES_USER: hrusr
            POSTGRES_PASSWORD: hrpwd
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
        volumes:
            - ./app/:/app/
        depends_on:
            db:
                condition: service_healthy
