\c hrdb;

-- --------------------------------------------------------------
-- DATA

INSERT INTO department_type (name) VALUES
('Board'),
('Division'),
('Team');

INSERT INTO department (name, description, code, top_level, parent, department_type) VALUES
('Sherpa_Inc', 'Sherpa, Inc.', 'Sherpa', TRUE, NULL, (SELECT id FROM department_type WHERE name = 'Board'));

INSERT INTO department (name, description, code, top_level, parent, department_type) VALUES
('Information Security', 'Responsible for information and systems security.', 'INFOSEC', FALSE, (SELECT id FROM department WHERE name = 'Sherpa_Inc'), (SELECT id FROM department_type WHERE name = 'Division')),
('Information Technology', 'Responsible for information and systems.', 'IT', FALSE, (SELECT id FROM department WHERE name = 'Sherpa_Inc'), (SELECT id FROM department_type WHERE name = 'Division')),
('Finance', 'Manages financial operations, accounting, and reporting.', 'FINANCE', FALSE, (SELECT id FROM department WHERE name = 'Sherpa_Inc'), (SELECT id FROM department_type WHERE name = 'Division')),
('Human Resources', 'Handles human resources, including recruitment and benefits.', 'HR', FALSE, (SELECT id FROM department WHERE name = 'Sherpa_Inc'), (SELECT id FROM department_type WHERE name = 'Division')),
('Marketing', 'Manages branding, advertising, and market research.', 'MKTG', FALSE, (SELECT id FROM department WHERE name = 'Sherpa_Inc'), (SELECT id FROM department_type WHERE name = 'Division')),
('Sales', 'Manages sales operations and client relationships.', 'SALES', FALSE, (SELECT id FROM department WHERE name = 'Sherpa_Inc'), (SELECT id FROM department_type WHERE name = 'Division'));

INSERT INTO department (name, description, code, top_level, parent, department_type) VALUES
('Security Operations', 'Monitors and responds to security incidents.', 'INFOSEC1', FALSE, (SELECT id FROM department WHERE code = 'INFOSEC'), (SELECT id FROM department_type WHERE name = 'Team')),
('Identity and Access Management', 'Manages digital identities, authentication and access controls.', 'INFOSEC2', FALSE, (SELECT id FROM department WHERE code = 'INFOSEC'), (SELECT id FROM department_type WHERE name = 'Team')),
('Governance, Risk and Compliance', 'Defines security policies and manages risk and regulatory compliance.', 'INFOSEC3', FALSE, (SELECT id FROM department WHERE code = 'INFOSEC'), (SELECT id FROM department_type WHERE name = 'Team')),
('Infrastructure', 'Operates servers, networks and cloud platforms.', 'IT1', FALSE, (SELECT id FROM department WHERE code = 'IT'), (SELECT id FROM department_type WHERE name = 'Team')),
('Service Desk', 'Provides end-user support and manages IT service requests.', 'IT2', FALSE, (SELECT id FROM department WHERE code = 'IT'), (SELECT id FROM department_type WHERE name = 'Team')),
('Software Development', 'Builds and maintains internal business applications.', 'IT3', FALSE, (SELECT id FROM department WHERE code = 'IT'), (SELECT id FROM department_type WHERE name = 'Team')),
('Facilities', 'Manages offices, equipment and physical infrastructure.', 'FINANCE1', FALSE, (SELECT id FROM department WHERE code = 'FINANCE'), (SELECT id FROM department_type WHERE name = 'Team')),
('Accounts Payable', 'Manages outgoing payments to vendors and suppliers.', 'FINANCE2', FALSE, (SELECT id FROM department WHERE code = 'FINANCE'), (SELECT id FROM department_type WHERE name = 'Team')),
('Accounts Receivable', 'Manages incoming payments and customer invoicing.', 'FINANCE3', FALSE, (SELECT id FROM department WHERE code = 'FINANCE'), (SELECT id FROM department_type WHERE name = 'Team')),
('Talent Acquisition', 'Manages recruitment, hiring and onboarding.', 'HR1', FALSE, (SELECT id FROM department WHERE code = 'HR'), (SELECT id FROM department_type WHERE name = 'Team')),
('Payroll and Benefits', 'Manages payroll, compensation and employee benefits.', 'HR2', FALSE, (SELECT id FROM department WHERE code = 'HR'), (SELECT id FROM department_type WHERE name = 'Team')),
('Brand and Communications', 'Manages brand identity, public relations and internal communications.', 'MKTG1', FALSE, (SELECT id FROM department WHERE code = 'MKTG'), (SELECT id FROM department_type WHERE name = 'Team')),
('Digital Marketing', 'Manages web, social media and online campaigns.', 'MKTG2', FALSE, (SELECT id FROM department WHERE code = 'MKTG'), (SELECT id FROM department_type WHERE name = 'Team')),
('Enterprise Sales', 'Manages relationships and deals with large corporate accounts.', 'SALES1', FALSE, (SELECT id FROM department WHERE code = 'SALES'), (SELECT id FROM department_type WHERE name = 'Team')),
('Inside Sales', 'Handles inbound leads and small and medium business sales.', 'SALES2', FALSE, (SELECT id FROM department WHERE code = 'SALES'), (SELECT id FROM department_type WHERE name = 'Team')),
('Sales Operations', 'Manages sales processes, forecasting and CRM tooling.', 'SALES3', FALSE, (SELECT id FROM department WHERE code = 'SALES'), (SELECT id FROM department_type WHERE name = 'Team'));

INSERT INTO position (name, description, code) VALUES
('CEO', 'Chief Executive Officer. Leads the company and its board of directors.', 'CEO'),
('CISO', 'Chief Information Security Officer. Directs the Information Security division.', 'CISO'),
('CIO', 'Chief Information Officer. Directs the Information Technology division.', 'CIO'),
('CFO', 'Chief Financial Officer. Directs the Finance division.', 'CFO'),
('HR Director', 'Directs the Human Resources division.', 'HRDIR'),
('CMO', 'Chief Marketing Officer. Directs the Marketing division.', 'CMO'),
('Sales Director', 'Directs the Sales division.', 'SALESDIR'),
('Security Operations Manager', 'Manages the Security Operations team.', 'SOCMGR'),
('IAM Manager', 'Manages the Identity and Access Management team.', 'IAMMGR'),
('GRC Manager', 'Manages the Governance, Risk and Compliance team.', 'GRCMGR'),
('Infrastructure Manager', 'Manages the Infrastructure team.', 'INFRAMGR'),
('Service Desk Manager', 'Manages the Service Desk team.', 'SDMGR'),
('Software Development Manager', 'Manages the Software Development team.', 'DEVMGR'),
('Facilities Manager', 'Manages the Facilities team.', 'FACMGR'),
('Accounts Payable Manager', 'Manages the Accounts Payable team.', 'APMGR'),
('Accounts Receivable Manager', 'Manages the Accounts Receivable team.', 'ARMGR'),
('Talent Acquisition Manager', 'Manages the Talent Acquisition team.', 'TAMGR'),
('Payroll and Benefits Manager', 'Manages the Payroll and Benefits team.', 'PAYMGR'),
('Brand Manager', 'Manages the Brand and Communications team.', 'BRANDMGR'),
('Digital Marketing Manager', 'Manages the Digital Marketing team.', 'DIGMGR'),
('Enterprise Sales Manager', 'Manages the Enterprise Sales team.', 'ENTMGR'),
('Inside Sales Manager', 'Manages the Inside Sales team.', 'INSMGR'),
('Sales Operations Manager', 'Manages the Sales Operations team.', 'SOPSMGR'),
('Security Analyst', 'Monitors, triages and responds to security events.', 'SOCAN'),
('IAM Analyst', 'Administers identities, accounts and access requests.', 'IAMAN'),
('GRC Analyst', 'Supports security policies, audits and risk assessments.', 'GRCAN'),
('Infrastructure Analyst', 'Operates and supports servers, networks and cloud platforms.', 'INFRAAN'),
('Service Desk Analyst', 'Provides first-line support to end users.', 'SDAN'),
('Systems Analyst', 'Analyzes requirements and develops internal applications.', 'SYSAN'),
('Facilities Analyst', 'Supports office, equipment and building operations.', 'FACAN'),
('Accounts Payable Analyst', 'Processes vendor invoices and outgoing payments.', 'APAN'),
('Accounts Receivable Analyst', 'Processes customer invoicing and collections.', 'ARAN'),
('Recruitment Analyst', 'Supports sourcing, screening and onboarding of candidates.', 'TAAN'),
('Payroll Analyst', 'Processes payroll and benefits administration.', 'PAYAN'),
('Brand Analyst', 'Supports branding, public relations and communications.', 'BRANDAN'),
('Digital Marketing Analyst', 'Runs and measures online marketing campaigns.', 'DIGAN'),
('Enterprise Sales Analyst', 'Supports enterprise account planning and proposals.', 'ENTAN'),
('Inside Sales Analyst', 'Qualifies inbound leads and supports SMB sales.', 'INSAN'),
('Sales Operations Analyst', 'Supports sales reporting, forecasting and CRM data.', 'SOPSAN');

INSERT INTO person (first_name,last_name,personal_email,id_number,tax_id,gender,birthdate) VALUES
('John','Lennon','john.lennon@example.com','15012345','20-15012345-3','M','1940-10-09'),
('Paul','McCartney','paul.mccartney@example.com','20023456','20-20023456-7','M','1942-06-18'),
('George','Harrison','george.harrison@example.com','25034567','20-25034567-1','M','1943-02-25'),
('Ringo','Starr','ringo.starr@example.com','30045678','20-30045678-5','M','1940-07-07');

INSERT INTO employee (person,start_date,position,department,department_relation) VALUES
((SELECT id FROM person WHERE personal_email='john.lennon@example.com'),'1960-08-18',(SELECT id FROM position WHERE name='IAM Analyst'),(SELECT id FROM department WHERE code='INFOSEC2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='paul.mccartney@example.com'),'1960-08-18',(SELECT id FROM position WHERE name='Inside Sales Analyst'),(SELECT id FROM department WHERE code='SALES2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='george.harrison@example.com'),'1960-08-18',(SELECT id FROM position WHERE name='Recruitment Analyst'),(SELECT id FROM department WHERE code='HR1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='ringo.starr@example.com'),'1962-08-14',(SELECT id FROM position WHERE name='Accounts Payable Analyst'),(SELECT id FROM department WHERE code='FINANCE2'),'MEMBER');

INSERT INTO person (first_name,last_name,personal_email,id_number,tax_id,gender,birthdate) VALUES
('Juan','Perez','jperez@example.com','10005','20-00010005-4','M','1993-10-01'),
('Maria','Rodriguez','mrodriguez@example.com','10006','27-00010006-4','F','1984-01-22'),
('Guillermo','Lopez','glopez@example.com','10007','20-00010007-4','M','1986-11-29'),
('Ana','Castro','acastro@example.com','10008','27-00010008-4','F','1995-08-31'),
('Roberto','Martinez','rmartinez@example.com','10009','20-00010009-4','M','1966-11-02'),
('Elena','Sosa','esosa@example.com','10010','27-00010010-4','F','1973-10-05'),
('Pedro','Lopez','plopez@example.com','10011','20-00010011-4','M','1999-11-05'),
('Juliana','Carrera','jcarrera@example.com','10012','27-00010012-4','F','1988-01-16'),
('Fabiana','Sanchez','fsanchez@example.com','10013','27-00010013-4','F','1969-07-24'),
('Jose','Valdez','jvaldez@example.com','10014','20-00010014-4','M','2000-07-02'),
('Raul','Mendez','rmendez@example.com','10015','20-00010015-4','M','1989-08-17'),
('Zoe','Prieto','zprieto@example.com','10016','27-00010016-4','F','1967-04-21'),
('Alonso','Luna','aluna@example.com','10017','20-00010017-4','M','1987-05-06'),
('Renata','Vargas','rvargas@example.com','10018','27-00010018-4','F','1983-09-22'),
('Ricardo','Lopez','rlopez@example.com','10019','20-00010019-4','M','1991-09-11'),
('Gabriela','Gomez','ggomez@example.com','10020','27-00010020-4','F','1974-03-12'),
('Javier','Garcia','jgarcia@example.com','10021','20-00010021-4','M','1983-12-07'),
('Marta','Torres','mtorres@example.com','10022','27-00010022-4','F','1988-03-09'),
('Rocio','Reyes','rreyes@example.com','10023','27-00010023-4','F','1994-11-05'),
('Carlos','Lopez','clopez@example.com','10024','20-00010024-4','M','1976-11-07'),
('Carmen','Alvarez','calvarez@example.com','10025','27-00010025-4','F','1979-03-14'),
('Julio','Villalba','jvillalba@example.com','10026','20-00010026-4','M','1984-10-11'),
('Sofia','Arias','sarias@example.com','10027','27-00010027-4','F','1972-06-19'),
('Luis','Vasquez','lvasquez@example.com','10028','20-00010028-4','M','1994-03-31'),
('Miguel','Vera','mvera@example.com','10029','20-00010029-4','M','1996-06-27'),
('Daniel','Cruz','dcruz@example.com','10030','20-00010030-4','M','1983-08-06'),
('Belen','Luna','bluna@example.com','10031','27-00010031-4','F','1978-07-11'),
('Alfredo','Serrano','aserrano@example.com','10032','20-00010032-4','M','1989-09-14'),
('Laura','Leiva','lleiva@example.com','10033','27-00010033-4','F','1996-10-12'),
('Olga','Gonzalez','ogonzalez@example.com','10034','27-00010034-4','F','1987-02-14'),
('Valeria','Quintero','vquintero@example.com','10035','27-00010035-4','F','1996-01-16'),
('Mario','Rios','mrios@example.com','10036','20-00010036-4','M','1995-04-01'),
('Alvaro','Beltran','abeltran@example.com','10037','20-00010037-4','M','1984-05-08'),
('Lucia','Perez','lperez@example.com','10038','27-00010038-4','F','1977-12-11'),
('Josefa','Parra','jparra@example.com','10039','27-00010039-4','F','1978-03-19'),
('Francisco','Gomez','fgomez@example.com','10040','20-00010040-4','M','1988-08-27'),
('Diego','Mendez','dmendez@example.com','10041','20-00010041-4','M','1984-09-12'),
('Gloria','Vera','gvera@example.com','10042','27-00010042-4','F','1997-07-27'),
('Yolanda','Gomez','ygomez@example.com','10043','27-00010043-4','F','1991-06-19'),
('Lidia','Barrera','lbarrera@example.com','10044','27-00010044-4','F','1985-12-11'),
('Nicolas','Reyes','nreyes@example.com','10045','20-00010045-4','M','1972-03-31'),
('Hector','Benitez','hbenitez@example.com','10046','20-00010046-4','M','1984-08-11'),
('Gabriela','Castro','gcastro@example.com','10047','27-00010047-4','F','1966-01-09'),
('Laura','Gomez','lgomez@example.com','10048','27-00010048-4','F','1980-10-17'),
('Fabio','Suarez','fsuarez@example.com','10049','20-00010049-4','M','1986-10-05'),
('Jorge','Torres','jtorres@example.com','10050','20-00010050-4','M','1981-04-12'),
('Clara','Serrano','cserrano@example.com','10051','27-00010051-4','F','1983-10-22'),
('Tatiana','Campos','tcampos@example.com','10052','27-00010052-4','F','1988-07-05'),
('Agustin','Gonzalez','agonzalez@example.com','10053','20-00010053-4','M','1981-01-05'),
('Vanesa','Bazan','vbazan@example.com','10054','27-00010054-4','F','1970-04-09'),
('Martin','Acosta','macosta@example.com','10055','20-00010055-4','M','1973-01-24'),
('Paula','Benitez','pbenitez@example.com','10056','27-00010056-4','F','1983-04-08'),
('Sebastian','Cabrera','scabrera@example.com','10057','20-00010057-4','M','1974-12-04'),
('Florencia','Dominguez','fdominguez@example.com','10058','27-00010058-4','F','2000-02-19'),
('Tomas','Escobar','tescobar@example.com','10059','20-00010059-4','M','1993-01-01'),
('Camila','Figueroa','cfigueroa@example.com','10060','27-00010060-4','F','1971-04-08'),
('Matias','Gimenez','mgimenez@example.com','10061','20-00010061-4','M','1998-10-01'),
('Victoria','Herrera','vherrera@example.com','10062','27-00010062-4','F','2001-04-23'),
('Ignacio','Ibarra','iibarra@example.com','10063','20-00010063-4','M','2000-07-08'),
('Agustina','Juarez','ajuarez@example.com','10064','27-00010064-4','F','1994-10-09'),
('Facundo','Ledesma','fledesma@example.com','10065','20-00010065-4','M','1966-03-23'),
('Micaela','Molina','mmolina@example.com','10066','27-00010066-4','F','1993-06-09'),
('Nahuel','Navarro','nnavarro@example.com','10067','20-00010067-4','M','1975-04-25'),
('Carolina','Ortiz','cortiz@example.com','10068','27-00010068-4','F','1987-02-03'),
('Emiliano','Paz','epaz@example.com','10069','20-00010069-4','M','1990-02-12'),
('Antonella','Quiroga','aquiroga@example.com','10070','27-00010070-4','F','1988-10-09'),
('Federico','Ramos','framos@example.com','10071','20-00010071-4','M','1968-12-15'),
('Luciana','Salinas','lsalinas@example.com','10072','27-00010072-4','F','2000-02-13'),
('Gonzalo','Toledo','gtoledo@example.com','10073','20-00010073-4','M','1971-09-10'),
('Milagros','Urquiza','murquiza@example.com','10074','27-00010074-4','F','1989-10-07'),
('Leandro','Vega','lvega@example.com','10075','20-00010075-4','M','1970-01-22'),
('Daniela','Zapata','dzapata@example.com','10076','27-00010076-4','F','1980-05-03'),
('Esteban','Aguirre','eaguirre@example.com','10077','20-00010077-4','M','1980-02-13'),
('Natalia','Blanco','nblanco@example.com','10078','27-00010078-4','F','1983-08-21'),
('Andres','Cardozo','acardozo@example.com','10079','20-00010079-4','M','1989-03-12'),
('Romina','Diaz','rdiaz@example.com','10080','27-00010080-4','F','1988-04-22'),
('Pablo','Ferreyra','pferreyra@example.com','10081','20-00010081-4','M','1983-12-22'),
('Silvina','Godoy','sgodoy@example.com','10082','27-00010082-4','F','1970-10-21'),
('Maximiliano','Ponce','mponce@example.com','10083','20-00010083-4','M','1976-09-24'),
('Mariana','Rojas','mrojas@example.com','10084','27-00010084-4','F','1981-03-15'),
('Cristian','Sosa','csosa@example.com','10085','20-00010085-4','M','1990-05-21'),
('Veronica','Medina','vmedina@example.com','10086','27-00010086-4','F','2001-04-22'),
('Hernan','Nunez','hnunez@example.com','10087','20-00010087-4','M','1986-01-08'),
('Cecilia','Ojeda','cojeda@example.com','10088','27-00010088-4','F','1968-06-13'),
('Damian','Peralta','dperalta@example.com','10089','20-00010089-4','M','1983-02-07'),
('Julieta','Rivas','jrivas@example.com','10090','27-00010090-4','F','2002-12-11'),
('Rodrigo','Suarez','rsuarez@example.com','10091','20-00010091-4','M','1979-11-16'),
('Lorena','Moreno','lmoreno@example.com','10092','27-00010092-4','F','1991-11-15'),
('Ezequiel','Correa','ecorrea@example.com','10093','20-00010093-4','M','1975-05-05'),
('Noelia','Farias','nfarias@example.com','10094','27-00010094-4','F','1981-12-18'),
('Santiago','Alvarez','salvarez@example.com','10095','20-00010095-4','M','2000-05-24'),
('Brenda','Castillo','bcastillo@example.com','10096','27-00010096-4','F','1993-10-13'),
('Franco','Miranda','fmiranda@example.com','10097','20-00010097-4','M','1989-04-05'),
('Melina','Villalba','mvillalba@example.com','10098','27-00010098-4','F','1998-08-03'),
('Joaquin','Ruiz','jruiz@example.com','10099','20-00010099-4','M','1969-02-05'),
('Abril','Mendoza','amendoza@example.com','10100','27-00010100-4','F','1976-11-14'),
('Bruno','Carrizo','bcarrizo@example.com','10101','20-00010101-4','M','1970-07-13'),
('Ivana','Luna','iluna@example.com','10102','27-00010102-4','F','1995-09-09'),
('Lautaro','Silva','lsilva@example.com','10103','20-00010103-4','M','2001-01-22'),
('Josefina','Romero','jromero@example.com','10104','27-00010104-4','F','1973-11-18');

INSERT INTO employee (person,start_date,position,department,department_relation) VALUES
((SELECT id FROM person WHERE personal_email='jperez@example.com'),'2025-09-01',(SELECT id FROM position WHERE name='Security Operations Manager'),(SELECT id FROM department WHERE code='INFOSEC1'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='glopez@example.com'),'2018-03-16',(SELECT id FROM position WHERE name='Brand Analyst'),(SELECT id FROM department WHERE code='MKTG1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='acastro@example.com'),'2020-08-19',(SELECT id FROM position WHERE name='Recruitment Analyst'),(SELECT id FROM department WHERE code='HR1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='rmartinez@example.com'),'2018-02-17',(SELECT id FROM position WHERE name='HR Director'),(SELECT id FROM department WHERE code='HR'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='plopez@example.com'),'2026-01-08',(SELECT id FROM position WHERE name='IAM Analyst'),(SELECT id FROM department WHERE code='INFOSEC2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='jcarrera@example.com'),'2020-11-22',(SELECT id FROM position WHERE name='Accounts Payable Manager'),(SELECT id FROM department WHERE code='FINANCE2'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='fsanchez@example.com'),'2024-08-10',(SELECT id FROM position WHERE name='CEO'),(SELECT id FROM department WHERE code='Sherpa'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='rmendez@example.com'),'2023-12-16',(SELECT id FROM position WHERE name='Payroll Analyst'),(SELECT id FROM department WHERE code='HR2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='zprieto@example.com'),'2023-02-13',(SELECT id FROM position WHERE name='Brand Manager'),(SELECT id FROM department WHERE code='MKTG1'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='aluna@example.com'),'2019-12-02',(SELECT id FROM position WHERE name='Infrastructure Analyst'),(SELECT id FROM department WHERE code='IT1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='rvargas@example.com'),'2018-02-07',(SELECT id FROM position WHERE name='CFO'),(SELECT id FROM department WHERE code='FINANCE'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='rlopez@example.com'),'2026-06-06',(SELECT id FROM position WHERE name='Systems Analyst'),(SELECT id FROM department WHERE code='IT3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='jgarcia@example.com'),'2017-01-14',(SELECT id FROM position WHERE name='Accounts Receivable Manager'),(SELECT id FROM department WHERE code='FINANCE3'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='mtorres@example.com'),'2016-01-21',(SELECT id FROM position WHERE name='GRC Analyst'),(SELECT id FROM department WHERE code='INFOSEC3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='rreyes@example.com'),'2026-07-03',(SELECT id FROM position WHERE name='Security Analyst'),(SELECT id FROM department WHERE code='INFOSEC1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='clopez@example.com'),'2017-06-17',(SELECT id FROM position WHERE name='CISO'),(SELECT id FROM department WHERE code='INFOSEC'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='jvillalba@example.com'),'2018-08-03',(SELECT id FROM position WHERE name='Digital Marketing Manager'),(SELECT id FROM department WHERE code='MKTG2'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='sarias@example.com'),'2024-06-20',(SELECT id FROM position WHERE name='CMO'),(SELECT id FROM department WHERE code='MKTG'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='lvasquez@example.com'),'2022-12-07',(SELECT id FROM position WHERE name='Inside Sales Analyst'),(SELECT id FROM department WHERE code='SALES2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='dcruz@example.com'),'2023-08-19',(SELECT id FROM position WHERE name='Payroll and Benefits Manager'),(SELECT id FROM department WHERE code='HR2'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='bluna@example.com'),'2023-07-24',(SELECT id FROM position WHERE name='IAM Manager'),(SELECT id FROM department WHERE code='INFOSEC2'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='aserrano@example.com'),'2025-07-01',(SELECT id FROM position WHERE name='Digital Marketing Analyst'),(SELECT id FROM department WHERE code='MKTG2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='lleiva@example.com'),'2024-09-17',(SELECT id FROM position WHERE name='Service Desk Manager'),(SELECT id FROM department WHERE code='IT2'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='ogonzalez@example.com'),'2020-08-21',(SELECT id FROM position WHERE name='Accounts Receivable Analyst'),(SELECT id FROM department WHERE code='FINANCE3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='mrios@example.com'),'2017-05-18',(SELECT id FROM position WHERE name='Digital Marketing Analyst'),(SELECT id FROM department WHERE code='MKTG2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='abeltran@example.com'),'2017-07-27',(SELECT id FROM position WHERE name='Sales Operations Manager'),(SELECT id FROM department WHERE code='SALES3'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='lperez@example.com'),'2020-12-25',(SELECT id FROM position WHERE name='GRC Manager'),(SELECT id FROM department WHERE code='INFOSEC3'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='jparra@example.com'),'2022-08-18',(SELECT id FROM position WHERE name='Infrastructure Manager'),(SELECT id FROM department WHERE code='IT1'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='dmendez@example.com'),'2021-08-01',(SELECT id FROM position WHERE name='Facilities Analyst'),(SELECT id FROM department WHERE code='FINANCE1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='gvera@example.com'),'2024-06-10',(SELECT id FROM position WHERE name='Service Desk Analyst'),(SELECT id FROM department WHERE code='IT2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='ygomez@example.com'),'2018-07-19',(SELECT id FROM position WHERE name='Enterprise Sales Analyst'),(SELECT id FROM department WHERE code='SALES1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='nreyes@example.com'),'2015-01-27',(SELECT id FROM position WHERE name='Sales Director'),(SELECT id FROM department WHERE code='SALES'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='hbenitez@example.com'),'2020-11-27',(SELECT id FROM position WHERE name='Inside Sales Manager'),(SELECT id FROM department WHERE code='SALES2'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='lgomez@example.com'),'2019-01-03',(SELECT id FROM position WHERE name='CIO'),(SELECT id FROM department WHERE code='IT'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='fsuarez@example.com'),'2026-05-21',(SELECT id FROM position WHERE name='Enterprise Sales Manager'),(SELECT id FROM department WHERE code='SALES1'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='jtorres@example.com'),'2017-05-21',(SELECT id FROM position WHERE name='Software Development Manager'),(SELECT id FROM department WHERE code='IT3'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='tcampos@example.com'),'2026-05-21',(SELECT id FROM position WHERE name='Sales Operations Analyst'),(SELECT id FROM department WHERE code='SALES3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='agonzalez@example.com'),'2019-06-18',(SELECT id FROM position WHERE name='Facilities Manager'),(SELECT id FROM department WHERE code='FINANCE1'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='vbazan@example.com'),'2018-06-06',(SELECT id FROM position WHERE name='Talent Acquisition Manager'),(SELECT id FROM department WHERE code='HR1'),'MANAGER'),
((SELECT id FROM person WHERE personal_email='macosta@example.com'),'2024-05-25',(SELECT id FROM position WHERE name='Security Analyst'),(SELECT id FROM department WHERE code='INFOSEC1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='pbenitez@example.com'),'2022-06-04',(SELECT id FROM position WHERE name='IAM Analyst'),(SELECT id FROM department WHERE code='INFOSEC2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='scabrera@example.com'),'2016-07-06',(SELECT id FROM position WHERE name='GRC Analyst'),(SELECT id FROM department WHERE code='INFOSEC3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='fdominguez@example.com'),'2025-01-24',(SELECT id FROM position WHERE name='Infrastructure Analyst'),(SELECT id FROM department WHERE code='IT1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='tescobar@example.com'),'2026-05-17',(SELECT id FROM position WHERE name='Service Desk Analyst'),(SELECT id FROM department WHERE code='IT2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='cfigueroa@example.com'),'2024-03-17',(SELECT id FROM position WHERE name='Systems Analyst'),(SELECT id FROM department WHERE code='IT3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='mgimenez@example.com'),'2020-11-10',(SELECT id FROM position WHERE name='Facilities Analyst'),(SELECT id FROM department WHERE code='FINANCE1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='vherrera@example.com'),'2024-03-12',(SELECT id FROM position WHERE name='Accounts Payable Analyst'),(SELECT id FROM department WHERE code='FINANCE2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='iibarra@example.com'),'2023-09-25',(SELECT id FROM position WHERE name='Accounts Receivable Analyst'),(SELECT id FROM department WHERE code='FINANCE3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='ajuarez@example.com'),'2024-01-20',(SELECT id FROM position WHERE name='Recruitment Analyst'),(SELECT id FROM department WHERE code='HR1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='fledesma@example.com'),'2017-08-01',(SELECT id FROM position WHERE name='Payroll Analyst'),(SELECT id FROM department WHERE code='HR2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='mmolina@example.com'),'2016-06-27',(SELECT id FROM position WHERE name='Brand Analyst'),(SELECT id FROM department WHERE code='MKTG1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='nnavarro@example.com'),'2024-05-08',(SELECT id FROM position WHERE name='Digital Marketing Analyst'),(SELECT id FROM department WHERE code='MKTG2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='cortiz@example.com'),'2012-04-19',(SELECT id FROM position WHERE name='Enterprise Sales Analyst'),(SELECT id FROM department WHERE code='SALES1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='epaz@example.com'),'2013-02-24',(SELECT id FROM position WHERE name='Inside Sales Analyst'),(SELECT id FROM department WHERE code='SALES2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='aquiroga@example.com'),'2019-02-25',(SELECT id FROM position WHERE name='Sales Operations Analyst'),(SELECT id FROM department WHERE code='SALES3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='framos@example.com'),'2020-03-05',(SELECT id FROM position WHERE name='Security Analyst'),(SELECT id FROM department WHERE code='INFOSEC1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='lsalinas@example.com'),'2025-09-06',(SELECT id FROM position WHERE name='IAM Analyst'),(SELECT id FROM department WHERE code='INFOSEC2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='gtoledo@example.com'),'2016-09-28',(SELECT id FROM position WHERE name='GRC Analyst'),(SELECT id FROM department WHERE code='INFOSEC3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='murquiza@example.com'),'2021-07-07',(SELECT id FROM position WHERE name='Infrastructure Analyst'),(SELECT id FROM department WHERE code='IT1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='lvega@example.com'),'2026-09-01',(SELECT id FROM position WHERE name='Service Desk Analyst'),(SELECT id FROM department WHERE code='IT2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='dzapata@example.com'),'2023-12-07',(SELECT id FROM position WHERE name='Systems Analyst'),(SELECT id FROM department WHERE code='IT3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='eaguirre@example.com'),'2023-05-13',(SELECT id FROM position WHERE name='Facilities Analyst'),(SELECT id FROM department WHERE code='FINANCE1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='nblanco@example.com'),'2022-11-12',(SELECT id FROM position WHERE name='Accounts Payable Analyst'),(SELECT id FROM department WHERE code='FINANCE2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='acardozo@example.com'),'2019-09-15',(SELECT id FROM position WHERE name='Accounts Receivable Analyst'),(SELECT id FROM department WHERE code='FINANCE3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='rdiaz@example.com'),'2013-04-08',(SELECT id FROM position WHERE name='Recruitment Analyst'),(SELECT id FROM department WHERE code='HR1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='pferreyra@example.com'),'2013-06-01',(SELECT id FROM position WHERE name='Payroll Analyst'),(SELECT id FROM department WHERE code='HR2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='sgodoy@example.com'),'2021-09-08',(SELECT id FROM position WHERE name='Brand Analyst'),(SELECT id FROM department WHERE code='MKTG1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='mponce@example.com'),'2021-04-01',(SELECT id FROM position WHERE name='Digital Marketing Analyst'),(SELECT id FROM department WHERE code='MKTG2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='mrojas@example.com'),'2013-12-21',(SELECT id FROM position WHERE name='Enterprise Sales Analyst'),(SELECT id FROM department WHERE code='SALES1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='csosa@example.com'),'2012-04-03',(SELECT id FROM position WHERE name='Inside Sales Analyst'),(SELECT id FROM department WHERE code='SALES2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='vmedina@example.com'),'2023-06-03',(SELECT id FROM position WHERE name='Sales Operations Analyst'),(SELECT id FROM department WHERE code='SALES3'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='hnunez@example.com'),'2020-04-09',(SELECT id FROM position WHERE name='Security Analyst'),(SELECT id FROM department WHERE code='INFOSEC1'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='cojeda@example.com'),'2022-08-07',(SELECT id FROM position WHERE name='IAM Analyst'),(SELECT id FROM department WHERE code='INFOSEC2'),'MEMBER'),
((SELECT id FROM person WHERE personal_email='dperalta@example.com'),'2020-03-24',(SELECT id FROM position WHERE name='GRC Analyst'),(SELECT id FROM department WHERE code='INFOSEC3'),'MEMBER');

INSERT INTO contractor (person,start_date,company_name,department) VALUES
((SELECT id FROM person WHERE personal_email='mrodriguez@example.com'),'2025-04-16',NULL,(SELECT id FROM department WHERE code='SALES2')),
((SELECT id FROM person WHERE personal_email='esosa@example.com'),'2020-07-13',NULL,(SELECT id FROM department WHERE code='HR1')),
((SELECT id FROM person WHERE personal_email='jvaldez@example.com'),'2025-10-09',NULL,(SELECT id FROM department WHERE code='MKTG2')),
((SELECT id FROM person WHERE personal_email='ggomez@example.com'),'2026-01-25',NULL,(SELECT id FROM department WHERE code='MKTG1')),
((SELECT id FROM person WHERE personal_email='calvarez@example.com'),'2018-06-06',NULL,(SELECT id FROM department WHERE code='SALES3')),
((SELECT id FROM person WHERE personal_email='mvera@example.com'),'2019-03-14',NULL,(SELECT id FROM department WHERE code='MKTG2')),
((SELECT id FROM person WHERE personal_email='vquintero@example.com'),'2024-03-31',NULL,(SELECT id FROM department WHERE code='MKTG1')),
((SELECT id FROM person WHERE personal_email='fgomez@example.com'),'2017-07-02',NULL,(SELECT id FROM department WHERE code='SALES1')),
((SELECT id FROM person WHERE personal_email='lbarrera@example.com'),'2025-03-05',NULL,(SELECT id FROM department WHERE code='IT3')),
((SELECT id FROM person WHERE personal_email='gcastro@example.com'),'2026-03-24',NULL,(SELECT id FROM department WHERE code='INFOSEC1')),
((SELECT id FROM person WHERE personal_email='cserrano@example.com'),'2021-09-10',NULL,(SELECT id FROM department WHERE code='HR2')),
((SELECT id FROM person WHERE personal_email='jrivas@example.com'),'2026-08-08',NULL,(SELECT id FROM department WHERE code='IT1')),
((SELECT id FROM person WHERE personal_email='rsuarez@example.com'),'2024-08-26',NULL,(SELECT id FROM department WHERE code='HR2')),
((SELECT id FROM person WHERE personal_email='lmoreno@example.com'),'2019-04-04',NULL,(SELECT id FROM department WHERE code='INFOSEC2')),
((SELECT id FROM person WHERE personal_email='ecorrea@example.com'),'2013-11-14',NULL,(SELECT id FROM department WHERE code='FINANCE3')),
((SELECT id FROM person WHERE personal_email='nfarias@example.com'),'2017-07-14',NULL,(SELECT id FROM department WHERE code='SALES3')),
((SELECT id FROM person WHERE personal_email='salvarez@example.com'),'2025-12-02',NULL,(SELECT id FROM department WHERE code='FINANCE1')),
((SELECT id FROM person WHERE personal_email='bcastillo@example.com'),'2025-11-21',NULL,(SELECT id FROM department WHERE code='SALES1')),
((SELECT id FROM person WHERE personal_email='fmiranda@example.com'),'2013-01-13',NULL,(SELECT id FROM department WHERE code='IT2')),
((SELECT id FROM person WHERE personal_email='mvillalba@example.com'),'2025-06-26',NULL,(SELECT id FROM department WHERE code='MKTG1')),
((SELECT id FROM person WHERE personal_email='jruiz@example.com'),'2025-02-08',NULL,(SELECT id FROM department WHERE code='INFOSEC3')),
((SELECT id FROM person WHERE personal_email='amendoza@example.com'),'2015-04-18',NULL,(SELECT id FROM department WHERE code='HR1')),
((SELECT id FROM person WHERE personal_email='bcarrizo@example.com'),'2019-03-14',NULL,(SELECT id FROM department WHERE code='INFOSEC1')),
((SELECT id FROM person WHERE personal_email='iluna@example.com'),'2019-05-15',NULL,(SELECT id FROM department WHERE code='FINANCE2')),
((SELECT id FROM person WHERE personal_email='lsilva@example.com'),'2024-02-15',NULL,(SELECT id FROM department WHERE code='SALES2')),
((SELECT id FROM person WHERE personal_email='jromero@example.com'),'2024-09-04',NULL,(SELECT id FROM department WHERE code='IT3'));
